on:
  pull_request:

name: Approve

jobs:
  approve:
    name: Auto-approve PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'coetzeevs'
    steps:
      - uses: actions/checkout@v3
      - name: Wait for checks to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.sha }}
          running-workflow-name: 'Auto-approve PR'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-regexp: ci-.+
          wait-interval: 20
      - name: Apply auto-approval
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved PR from workflow"
          github-token: ${{ secrets.ACTION_TOKEN_V2 }}
